### ISSUE TITLE
Some components are listed on JLCPCB site, but can't be found with this tool

### ISSUE THREAD

**Issue by karolzlot** [yaqwsx/jlcparts#69]
For example:
```
C115170 (Z-21310110021001)

C2835315
```

**Comment by yaqwsx** [comment]
It means that the component is not available in the table that JLC PCB provides (https://jlcpcb.com/componentSearch/uploadComponentInfo). Please, let them know. There is nothing I can do about it.

**Comment by yaqwsx** [comment]
We migrated to the new JLC PCB API. Otherwise, there is nothing else we can do.

**Comment by zwn** [comment]
A comment here
- https://github.com/yaqwsx/jlcparts/issues/73#issuecomment-1272468792

states that it is expected that some parts are ignored (due to performance reasons). Since we do not have access to the new API we cannot independently verify if the component is missing on the jlcpcb side or not.

A clarification of what can be currently expected from the tool would be much appreciated. Thanks.
