### ISSUE TITLE
Docker - YAML file

### ISSUE THREAD

**Issue by CzarnyLewis** [yaqwsx/jlcparts#96]
I have been trying to run JLCParts in Docker for several hours. Unfortunately, I don't know what the YAML file should look like. Does anyone know:
- what ports to map?
- what path to map?
- what environment to set?
Thank you

**Comment by yaqwsx** [comment]
What are you trying to achieve? The CI of this project builds a static website. There is no backend. Just plain-old static website that is enough to just serve via any HTTP server.

**Comment by CzarnyLewis** [comment]
I see there is a Dockerfile, so I thought it was cool to have a actual library of electronic components in a container.

**Comment by yaqwsx** [comment]
That was dockerfile specifying the run environment for Travis CI we no longer use (I removed it as it is no longer relevant).

The build process is described in https://github.com/yaqwsx/jlcparts/blob/master/.github/workflows/update_components.yaml

Since running this inside Docker makes no sense (there is no backend to run), I close this issue.
